# Generated by Django 5.1.4 on 2025-01-21 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.CharField(choices=[('SBI', 'State Bank Of India'), ('HD', 'HDFC'), ('AX', 'AXIS'), ('CNR', 'canara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.CharField(choices=[('HL', 'Home LONE'), ('PL', 'Personal Loan'), ('CL', 'Car Loan'), ('BL', 'Business Loan'), ('RF', 'Re-Fenace')], max_length=20),
        ),
    ]
