# Generated by Django 5.1.4 on 2025-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_delete_customer_delete_dsa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsa_name', models.CharField(max_length=50)),
                ('dsa_code', models.CharField(max_length=50)),
                ('dsa_phone_number', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
