# Generated by Django 5.1.4 on 2025-01-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('product', models.CharField(choices=[('HL', 'Home LONE'), ('PL', 'Personal Loan'), ('CL', 'Car Loan'), ('BL', 'Business Loan'), ('RF', 'Re-Fenace')], max_length=20)),
                ('bank', models.CharField(choices=[('SBI', 'State Bank Of India'), ('HD', 'HDFC'), ('AX', 'AXIS'), ('CNR', 'canara')], max_length=20)),
                ('status', models.CharField(choices=[('login_submit', 'Login Submit'), ('login_complete', 'Login Complete'), ('tec_completed', 'TEC Completed'), ('legal_completed', 'Legal Completed'), ('disp', 'Dispatched'), ('reject', 'Rejected')], max_length=20)),
                ('type', models.CharField(choices=[('DSA', 'DSA'), ('SELF', 'Self')], max_length=4)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('dsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.dsa')),
            ],
        ),
    ]
