# Generated by Django 5.1.4 on 2025-02-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_task_alter_customer_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
