# Generated by Django 5.1.4 on 2025-02-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
